/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "spi_driver.h"
#include "stm32f411_drivers.h"
#include <stdint.h>

uint8_t audio_buffer[512];

PCM_Frame_t frame;
WAV_t wav;
File_t file;
FileSystem_t fs;
SD_Handle_t sdHandler;

I2S_Handle_t I2S5Handler;
PLLI2S_Handle_t PLLI2S5Handler;
GPIO_Handle_t I2S5GPIO;

SPI_Handle_t SPI2Handler;
GPIO_Handle_t SPI22GPIO;
GPIO_Handle_t CSGPIO;

TIMx_Handle_t TIM9Handler;

GPIO_Handle_t GpioLed;
GPIO_Handle_t GpioLed2;
GPIO_Handle_t GpioBtn;

GPIO_Handle_t USART2GPIO;
USART_Handle_t USART2Handler;
uint8_t bufferMult[4096] = {};
uint8_t buffer[512] = {};
uint8_t msg_eof[512] = "FS_EOF\r\n";
uint8_t msg_error[512] = "ERROR\r\n";
ringBuffer_t rb;
uint8_t usart2_error_flag = 0;

volatile uint8_t cnt = 0;
volatile uint8_t debounce_cnt = 0;
volatile uint8_t debounce_active = 0;
volatile uint8_t debounce_ready = 0;
void buffer_init(){
	int i = 0;
	int cnt = 0;
	while(i < 512){
		cnt = 0;
		while(cnt < 24 && i < 512){
			audio_buffer[i+0] = 0x40;
			audio_buffer[i+1] = 0x1F;
			audio_buffer[i+2] = 0x40;
			audio_buffer[i+3] = 0x1F;
			cnt++;
			i+=4;
		}
		cnt = 0;
		while(cnt < 24 && i < 512){
			audio_buffer[i+0] = 0xC0;
			audio_buffer[i+1] = 0xE0;
			audio_buffer[i+2] = 0xC0;
			audio_buffer[i+3] = 0xE0;
			cnt++;
			i+=4;
		}
	}

}
void i2s5_init(void){
	I2S5GPIO.pGPIOx = GPIOB;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinPuPdCtlr  	= GPIO_NO_PUPD;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinOPType    	= GPIO_OPT_PP;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinSpeed     	= GPIO_SPEED_FST;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN0;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_ALTFUN;
	I2S5GPIO.GPIO_PinConfig.GPIO_PinAltFunMode= GPIO_AF6;
	
	GPIO_Init(&I2S5GPIO); //CK

	I2S5GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN1;
	GPIO_Init(&I2S5GPIO); //WS
	
	I2S5GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN8;
	GPIO_Init(&I2S5GPIO); //SD

	PLLI2S5Handler.PLLI2SR = 5;
	PLLI2S5Handler.PLLI2SM = 8;
	PLLI2S5Handler.PLLI2SN = 238;
	I2S_PLLConfig(&PLLI2S5Handler);

	I2S5Handler.pI2Sx = SPI5;
	I2S5Handler.I2SConfig.I2S_ConfigMode = I2S_CFG_MASTER_TX;
	I2S5Handler.I2SConfig.I2S_Standard = I2S_STD_PHILIPS;
	I2S5Handler.I2SConfig.I2S_ClockPolarity = I2S_CKPOL_LOW;
	I2S5Handler.I2SConfig.I2S_DataLen = I2S_DATALEN_16BITS;
	I2S5Handler.I2SConfig.I2S_ChannelLen = I2S_CHLEN_16BITS;
	I2S5Handler.I2SConfig.I2S_SampleRate = I2S_SAMPLE_RATE_48K;
	I2S5Handler.I2SConfig.I2S_MCLK_Enable = I2S_MCKOE_DISABLE;

	I2S_Init(&I2S5Handler);
}

void gpio_init(void){
	// Configurar PA5 como Salida Push-Pull
	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed     = GPIO_SPEED_FST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType    = GPIO_OPT_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdCtlr  = GPIO_NO_PUPD;

	GPIO_Init(&GpioLed);
	GpioLed2.pGPIOx = GPIOA;
	GpioLed2.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN6;
	GpioLed2.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_OUT;
	GpioLed2.GPIO_PinConfig.GPIO_PinSpeed     = GPIO_SPEED_FST;
	GpioLed2.GPIO_PinConfig.GPIO_PinOPType    = GPIO_OPT_PP;
	GpioLed2.GPIO_PinConfig.GPIO_PinPuPdCtlr  = GPIO_NO_PUPD;

	GPIO_Init(&GpioLed2);
	GpioLed2.pGPIOx = GPIOA;
	GpioLed2.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN7;
	GpioLed2.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_OUT;
	GpioLed2.GPIO_PinConfig.GPIO_PinSpeed     = GPIO_SPEED_FST;
	GpioLed2.GPIO_PinConfig.GPIO_PinOPType    = GPIO_OPT_PP;
	GpioLed2.GPIO_PinConfig.GPIO_PinPuPdCtlr  = GPIO_NO_PUPD;

	GPIO_Init(&GpioLed2);

	// Configurar PC13 como Entrada
	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN13;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_IT_FT;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdCtlr  = GPIO_NO_PUPD;

	GPIO_Init(&GpioBtn);

	NVIC_IRQInterruptConfig(IRQ_NO_EXTI15_10, ENABLE);
	NVIC_IRQPriorityConfig(IRQ_NO_EXTI15_10, NVIC_IRQ_PRI15);
}
void usart2_init(){

	USART2GPIO.pGPIOx = GPIOA;
	USART2GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN2;
	USART2GPIO.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_ALTFUN;
	USART2GPIO.GPIO_PinConfig.GPIO_PinAltFunMode= GPIO_AF7;
	USART2GPIO.GPIO_PinConfig.GPIO_PinPuPdCtlr  = GPIO_NO_PUPD;
	USART2GPIO.GPIO_PinConfig.GPIO_PinOPType    = GPIO_OPT_PP;
	USART2GPIO.GPIO_PinConfig.GPIO_PinSpeed     = GPIO_SPEED_FST;
	GPIO_Init(&USART2GPIO);

	USART2GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN3;
	GPIO_Init(&USART2GPIO);

	USART2Handler.pUSARTx = USART2;
	USART2Handler.USART_PinConfig.USARTx_Mode 		= USART_MODE_TXRX;
	USART2Handler.USART_PinConfig.USARTx_BaudRate 	= USART_STD_BAUD_115200;
	USART2Handler.USART_PinConfig.USARTx_WordLength = USART_WORDLEN_8BITS;
	USART2Handler.USART_PinConfig.USARTx_ParityCtrl = USART_PARITY_DISABLE;
	USART2Handler.USART_PinConfig.USARTx_StopBits 	= USART_STOPBITS_1;
	USART2Handler.USART_PinConfig.USARTx_RXInterruptEnable 	= USART_IRQ_ENABLE;

	USART_Init(&USART2Handler);

	ringBuffer_init(&rb);

	NVIC_IRQInterruptConfig(IRQ_NO_USART2, ENABLE);
	NVIC_IRQPriorityConfig(IRQ_NO_USART2, NVIC_IRQ_PRI15);
}
void tim9_init(){
	TIM9Handler.pTIMx = TIM9;
	TIM9Handler.TIMx_Config.TIMx_Prescaler = 15;
	TIM9Handler.TIMx_Config.TIMx_AutoReload = 9999;
	TIM9Handler.TIMx_Config.TIMx_UpdateInterruptEnable = ENABLE;

	TIMx_Init(&TIM9Handler);

	NVIC_IRQInterruptConfig(IRQ_NO_TIM1_BRK_TIM9, ENABLE);
	NVIC_IRQPriorityConfig(IRQ_NO_TIM1_BRK_TIM9, NVIC_IRQ_PRI15);
}
void spi2_init(){
	CSGPIO.pGPIOx = GPIOB;
	CSGPIO.GPIO_PinConfig.GPIO_PinNum       	= GPIO_PIN12;
	CSGPIO.GPIO_PinConfig.GPIO_PinMode      	= GPIO_MODE_OUT;
	CSGPIO.GPIO_PinConfig.GPIO_PinPuPdCtlr  	= GPIO_NO_PUPD;
	CSGPIO.GPIO_PinConfig.GPIO_PinOPType    	= GPIO_OPT_PP;
	CSGPIO.GPIO_PinConfig.GPIO_PinSpeed     	= GPIO_SPEED_FST;

	GPIO_Init(&CSGPIO); //CS

	SPI22GPIO.pGPIOx = GPIOB;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinPuPdCtlr  	= GPIO_NO_PUPD;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinOPType    	= GPIO_OPT_PP;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinSpeed     	= GPIO_SPEED_FST;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN13;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinMode      = GPIO_MODE_ALTFUN;
	SPI22GPIO.GPIO_PinConfig.GPIO_PinAltFunMode= GPIO_AF5;

	GPIO_Init(&SPI22GPIO); //SCK

	SPI22GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN14;
	GPIO_Init(&SPI22GPIO); //MISO

	SPI22GPIO.GPIO_PinConfig.GPIO_PinNum       = GPIO_PIN15;
	GPIO_Init(&SPI22GPIO); //MOSI

	SPI2Handler.pSPIx = SPI2;
	SPI2Handler.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI2Handler.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SPI2Handler.SPIConfig.SPI_FirstBit = SPI_MSBFIRST;
	SPI2Handler.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
	SPI2Handler.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI2Handler.SPIConfig.SPI_SSM = SPI_SSM_EN;
	SPI2Handler.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV64;

	SPI_Init(&SPI2Handler);
}
void sdCard_init(){
	sdHandler.pSPIHandle = &SPI2Handler;
	sdHandler.pCSHandle = &CSGPIO;

}

uint8_t hex2ascii(uint8_t nibble){
	if(nibble < 10){
		return nibble + '0';
	}
	else{
		return (nibble-10) + 'A';
	}
}

void PrintHex(USART_Handle_t *pUSARTx, uint8_t value){

	uint8_t hex[3];

	hex[0] = hex2ascii((value >> 4) & 0x0F);
	hex[1] = hex2ascii(value & 0x0F);
	hex[2] = ' ';

	USART_SendData(&USART2Handler, hex, 3);
}

int main(void)
{
	uint8_t space[2] = "\r\n";
	uint8_t error[6] = "ERROR\n";
	// uint16_t validBytes = 0;
//	uint32_t FirstCluster = 0;
	gpio_init();
	usart2_init();
	tim9_init();
	spi2_init();
	sdCard_init();
	i2s5_init();
	buffer_init();
	if(SD_Init(&sdHandler) == cmd_ok){
		sdHandler.pSPIHandle->pSPIx->CR1 &= ~(1U << SPI_CR1_SPE);          
		sdHandler.pSPIHandle->SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;
		sdHandler.pSPIHandle->pSPIx->CR1 &= ~(0x7U << SPI_CR1_BR);
		sdHandler.pSPIHandle->pSPIx->CR1 |= (sdHandler.pSPIHandle->SPIConfig.SPI_SclkSpeed << SPI_CR1_BR);
		sdHandler.pSPIHandle->pSPIx->CR1 |= (1U << SPI_CR1_SPE);
	}
	// Init_Filesystem(&sdHandler, &fs);
	// OpenFile(&fs, &file,"DARDOS  WAV");

	// if(WAV_Open(&file, &wav) == wav_ok){
	// 	GPIO_WriteToOutputPin(GPIOA, GPIO_PIN7, 1);
	// }
	// else
	// {
	// 	GPIO_WriteToOutputPin(GPIOA, GPIO_PIN7, 0);
	// }

	PrintHex(&USART2Handler, (wav.startData >> 24) & 0xFF);
	PrintHex(&USART2Handler, (wav.startData >> 16) & 0xFF);
	PrintHex(&USART2Handler, (wav.startData >> 8) & 0xFF);
	PrintHex(&USART2Handler, (wav.startData >> 0) & 0xFF);
	USART_SendData(&USART2Handler, space, 2);

	int cnt = 0;
	while(cnt < 0xC000){
		if(WAV_ReadFrame(&wav, &frame) != frame_ok){
			USART_SendData(&USART2Handler, error, 6);
			break;
		}
		if(frame.left_frame != 0 || frame.rigth_frame != 0){
			PrintHex(&USART2Handler, (frame.left_frame >> 8) & 0xFF);
			PrintHex(&USART2Handler, frame.left_frame & 0xFF);

			USART_SendData(&USART2Handler, space, 2);

			PrintHex(&USART2Handler, (frame.rigth_frame >> 8) & 0xFF);
			PrintHex(&USART2Handler, frame.rigth_frame & 0xFF);

			USART_SendData(&USART2Handler, space, 2);

			PrintHex(&USART2Handler, (cnt >> 24) & 0xFF);
			PrintHex(&USART2Handler, (cnt >> 16) & 0xFF);
			PrintHex(&USART2Handler, (cnt >> 8) & 0xFF);
			PrintHex(&USART2Handler, cnt & 0xFF);
			USART_SendData(&USART2Handler, space, 2);
			break;
		}
		cnt++;
	}
	int i = 0;
    while(1){
		if(i < 512){
			int16_t leftFrame = (int16_t)((uint16_t)audio_buffer[i + 1] << 8 | (uint16_t)audio_buffer[i]);
			int16_t rightFrame = (int16_t)((uint16_t)audio_buffer[i + 3] << 8 | (uint16_t)audio_buffer[i + 2]);
			
			while (!(I2S5Handler.pI2Sx->SR & I2S_FLAG_TXE));
			I2S5Handler.pI2Sx->DR = leftFrame;
			while (!(I2S5Handler.pI2Sx->SR & I2S_FLAG_TXE));
			I2S5Handler.pI2Sx->DR = rightFrame ;
			i += 4;
		}
		else{
			i = 0;
		}



    	if(cnt >= 50){
    		GPIO_ToggleOutputPin(GpioLed.pGPIOx, GPIO_PIN5);
    		cnt = 0;
    	}

    	if(debounce_ready){
    		debounce_ready = 0;

    		if(!GPIO_ReadFromInputPin(GpioBtn.pGPIOx, GPIO_PIN13)){
    			GPIO_ToggleOutputPin(GpioLed2.pGPIOx, GPIO_PIN6);
				USART_SendData(&USART2Handler, msg_eof, 1);
    		}
    		EXTI->IMR |= (1U << GPIO_PIN13);
    	}

    };

    return 0;
}

void TIM1_BRK_TIM9_IRQHandler(void){
	if(TIM9->SR & TIM_FLAG_UIF){
		cnt++;
		if(debounce_active){
			debounce_cnt--;
			if(debounce_cnt <= 0){
				debounce_ready = SET;
				debounce_active = 0;
			}
		}
		TIM9->SR &= ~TIM_FLAG_UIF;
	}
}

void USART2_IRQHandler(){
	if(USART2->SR & USART_FLAG_RXNE){
		if(ringBuffer_push(&rb, USART2->DR) == rb_full){
			usart2_error_flag = 1;
		}
	}
}

void EXTI15_10_IRQHandler(){

	if(EXTI->PR & (1 << 13)){
		EXTI->IMR &= ~(1U << 13);
		debounce_cnt = 2;
		debounce_active = SET;
		GPIO_IRQHandling(13);
	}
}
